version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"  # default rabbitmq port
      - "15672:15672" # rabbitmq management ui
    networks:
      - app-network


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - api-gateway

  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      - rabbitmq

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    networks:
      - app-network
    depends_on:
      - rabbitmq


  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    networks:
      - app-network
    depends_on:
      - rabbitmq



  notification-service:
    build: ./notification-service
    ports:
      - "5004:5004"
    env_file: ./notification-service/.env
    networks:
      - app-network
    depends_on:
      - rabbitmq



  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - rabbitmq
      - auth-service
      - product-service
      - order-service

  

networks:
  app-network:
    driver: bridge
