apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    name: product-service
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo "Waiting for RabbitMQ..."; sleep 2; done']
      containers:
        - name: product-service
          image: shamnads306/ecom-product-service:latest
          ports:
            - containerPort: 5002
          
            