apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    name: product-service
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ecommerce-microservice_product-service:latest
          ports:
            -containerPort: 5002
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
            