apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: order-service
      template:
        metadata:
          labels:
            app: order-service
        spec:
          containers:
            - name: order-service
              image: ecommerce-microservice_order-service:latest
              ports:
                - containerPort: 5003
              livenessProbe:
                httpGet:
                  path: /health
                  port: 5003
                initialDelaySeconds: 5
                periodSeconds: 10

              readinessProbe:
                httpGet:
                  path: /health
                  port: 5003
                initialDelaySeconds: 5
                periodSeconds: 10

