name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Tests
      - name: Run Tests
        run: npm test

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test  # Run only after the build-test job succeeds

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Images
      - name: Build and Push Docker Images
        run: |
          # Build Images for all services
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-auth-service:latest ./auth-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-product-service:latest ./product-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-order-service:latest ./order-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-notification-service:latest ./notification-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-frontend-service:latest ./frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecom-apigateway-service:latest ./api-gateway

          # Push images to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/ecom-auth-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ecom-product-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ecom-order-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ecom-notification-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ecom-frontend-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ecom-apigateway-service:latest
